### PR TITLE
added supra vrf documentation

### PR DESCRIPTION
**Pull request by ksdumont**
**Description**

Added Supra's VRF documentation. 

**Additional context**

Adding a resource for developers.

### CODE REVIEW

**Comment by sbvegan** [comment]
Hey @ksdumont sorry for letting this sit. I'd like to carve out a tutorial specific section. I'll do that today and direct the PR to move there!

**Comment by ksdumont** [comment]
No worries! Thanks for the heads up.

**Comment by sbvegan** [comment]
Alright! I reorganized the community directory, can you please follow the [contributing doc](https://github.com/ethereum-optimism/developers/blob/main/docs/CONTRIBUTING.md) to carve out your own section in the `community/tutorials` section?

**Comment by ksdumont** [comment]
Just opened a new PR here: https://github.com/ethereum-optimism/developers/pull/43

**Pull request closed without merging**
